### ISSUE TITLE
Audio doesn't mute if the game is in the background on startup

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#221]
The title says it all. This is not the case with any other tileflip transition in the game.

**Comment by Luke18033** [comment]
This seems to generally be a problem with the game always assuming it's focused when first launched - if you add a `map` command to your launch parameters, launch it, then switch out of focus, the game will keep trying to recenter your mouse.

**Comment by SpyceTewan** [comment]
Can you try on latest build?

**Comment by Luke18033** [comment]
Still an issue

**Comment by CitadelCore** [comment]
Does not happen for me so assuming it's fixed in the latest version. Re-open if it happens again.

**Comment by Luke18033** [comment]
On the latest build, audio still doesn't get muted if you tab out of the game before it's done loading.

**Comment by Luke18033** [comment]
Replaced with more detailed ChaosInitiative/Chaos-Source#452
