### ISSUE TITLE
Fix buildmodelforworld

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#225]
This command is supposed to generate the world impostors used in splitscreen for recursive portal views and goo reflections, but it doesn't work. The game complains about being unable to remove a bunch of files which never existed in the first place, and only a single VMT is packed into the map, with no accompanying VTFs or an actual model.

**Comment by Luke18033** [comment]
Running the command in P2CE generates some additional errors related to studiomdl, but otherwise behaves the same.

**Comment by CitadelCore** [comment]
Fixed (as far as I can see).
![image](https://user-images.githubusercontent.com/5567402/88632062-0334d300-d0ab-11ea-9eb8-01d728946170.png)

**Comment by Luke18033** [comment]
Still broken for me

**Comment by CitadelCore** [comment]
In what way?

**Comment by Luke18033** [comment]
Same issue as before, the game complains about not being able to delete a bunch of files which never existed, and only a single VMT gets packed.

**Comment by CitadelCore** [comment]
Can't reproduce this, I tested it again and it's still working fine. Could someone else please test?

**Comment by Luke18033** [comment]
Still an issue. The following is everything that appears in the console when running the command in `sp_a2_portal_room`, which is located in the mounted folder `portal2_dlc4`:
```
[engine] Failed compiling d:\steamlibrary\steamapps\common\portal 2 community edition\content\p2ce\models\maps\sp_a2_portal_room/simpleworldmodel_water.qc
[engine] Failed compiling d:\steamlibrary\steamapps\common\portal 2 community edition\content\p2ce\models\maps\sp_a2_portal_room/simpleworldmodel.qc
[engine] Unable to remove d:\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel.mdl! (errno 2)
[engine] Unable to remove d:\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel.dx90.vtx! (errno 2)
[engine] Unable to remove d:\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel.vvd! (errno 2)
[engine] Unable to remove d:\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel_water.mdl! (errno 2)
[engine] Unable to remove d:\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel_water.dx90.vtx! (errno 2)
[engine] Unable to remove d:\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel_water.vvd! (errno 2)
```
For comparison, vanilla P2 prints the following instead on the same map:
```
Compilation of "d:\steamlibrary\steamapps\common\content\portal2_dlc4\materialsrc\models\maps\sp_a2_portal_room/simpleworldmodel.tga" succeeded
Compilation of "d:\steamlibrary\steamapps\common\content\portal2_dlc4\materialsrc\models\maps\sp_a2_portal_room/simpleworldmodel_lightmap.tga" succeeded
Compilation of "d:\steamlibrary\steamapps\common\content\portal2_dlc4\materialsrc\models\maps\sp_a2_portal_room/simpleworldmodel_albedo.tga" succeeded
Compilation of "d:\steamlibrary\steamapps\common\content\portal2_dlc4\models\maps\sp_a2_portal_room/simpleworldmodel_water.qc" succeeded
Compilation of "d:\steamlibrary\steamapps\common\content\portal2_dlc4\models\maps\sp_a2_portal_room/simpleworldmodel.qc" succeeded
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/models/maps/sp_a2_portal_room/simpleworldmodel.mdl! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/models/maps/sp_a2_portal_room/simpleworldmodel.dx90.vtx! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/models/maps/sp_a2_portal_room/simpleworldmodel.vvd! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/models/maps/sp_a2_portal_room/simpleworldmodel_water.mdl! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/models/maps/sp_a2_portal_room/simpleworldmodel_water.dx90.vtx! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/models/maps/sp_a2_portal_room/simpleworldmodel_water.vvd! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/materials/models/maps/sp_a2_portal_room/simpleworldmodel.pwl.vtf! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/materials/models/maps/sp_a2_portal_room/simpleworldmodel.vtf! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/materials/models/maps/sp_a2_portal_room/simpleworldmodel_albedo.pwl.vtf! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/materials/models/maps/sp_a2_portal_room/simpleworldmodel_albedo.vtf! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/materials/models/maps/sp_a2_portal_room/simpleworldmodel_lightmap.pwl.vtf! (errno 2)
Unable to remove d:\steamlibrary\steamapps\common\portal 2\portal2_dlc4/materials/models/maps/sp_a2_portal_room/simpleworldmodel_lightmap.vtf! (errno 2)
```
P2CE no longer shows any errors related to the materials, although they still don't seem to be generated/packed. The models now "fail compiling" as well, though again that's effectively meaningless since nothing was generated anyway.

**Comment by Luke18033** [comment]
Before anyone says this is a useless old feature meant for Xbox, it does have a real potential use in maps which want to have a lot of portals visible at once, since switching to an extremely simple model for the farther away portal views could really help performance.

**Comment by luxeleios** [comment]
Isn't this feature used in all water reflections...? I thought that's how they changed the reflections in P2

**Comment by JJL772** [comment]
This may have been fixed recently, gonna have to test it in the next release

**Comment by Luke18033** [comment]
Still broken

**Comment by Luke18033** [comment]
Still broken
```
[engine] Compilation of "d:\games\steamlibrary\steamapps\common\portal 2 community edition\content\p2ce\models\maps\sp_a2_portal_room/simpleworldmodel_water.qc" succeeded
[engine] Compilation of "d:\games\steamlibrary\steamapps\common\portal 2 community edition\content\p2ce\models\maps\sp_a2_portal_room/simpleworldmodel.qc" succeeded
[engine] Unable to remove d:\games\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel.mdl! (errno 2)
[engine] Unable to remove d:\games\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel.dx90.vtx! (errno 2)
[engine] Unable to remove d:\games\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel.vvd! (errno 2)
[engine] Unable to remove d:\games\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel_water.mdl! (errno 2)
[engine] Unable to remove d:\games\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel_water.dx90.vtx! (errno 2)
[engine] Unable to remove d:\games\steamlibrary\steamapps\common\portal 2 community edition\p2ce/models/maps/sp_a2_portal_room/simpleworldmodel_water.vvd! (errno 2)
```
Also, turns out world impostors are actually used on PC too on low graphics settings, so it wouldn't just be for maps with lots of portals.

**Comment by Luke18033** [comment]
The fact that it worked for Citadel earlier makes me think that maybe it only works correctly in debug builds for some reason? Or something is messed up with my files, but as far as I'm aware it's never worked for anyone else either, besides TeamSpen once a long time ago.
